// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwnOQ4mNJq8HYAvF-7KKKFhYRMN4U6go0',
    appId: '1:758372397368:web:de69310dfc8e317716d1cd',
    messagingSenderId: '758372397368',
    projectId: 'contacts-app-57d03',
    authDomain: 'contacts-app-57d03.firebaseapp.com',
    storageBucket: 'contacts-app-57d03.firebasestorage.app',
    measurementId: 'G-2CK29S10JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIPuHIwrpSKD1Y_5nTWOj3gMvd_e9KzZU',
    appId: '1:758372397368:android:b5a691927a50792316d1cd',
    messagingSenderId: '758372397368',
    projectId: 'contacts-app-57d03',
    storageBucket: 'contacts-app-57d03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPnMz-ywS6HU6MDp4n2uPI4Djf1WJF9Mc',
    appId: '1:758372397368:ios:cab505aca8ec31db16d1cd',
    messagingSenderId: '758372397368',
    projectId: 'contacts-app-57d03',
    storageBucket: 'contacts-app-57d03.firebasestorage.app',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPnMz-ywS6HU6MDp4n2uPI4Djf1WJF9Mc',
    appId: '1:758372397368:ios:cab505aca8ec31db16d1cd',
    messagingSenderId: '758372397368',
    projectId: 'contacts-app-57d03',
    storageBucket: 'contacts-app-57d03.firebasestorage.app',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwnOQ4mNJq8HYAvF-7KKKFhYRMN4U6go0',
    appId: '1:758372397368:web:d248caa101e77d0116d1cd',
    messagingSenderId: '758372397368',
    projectId: 'contacts-app-57d03',
    authDomain: 'contacts-app-57d03.firebaseapp.com',
    storageBucket: 'contacts-app-57d03.firebasestorage.app',
    measurementId: 'G-KQ3TSRYJ8J',
  );
}
